# fly.toml app configuration file generated for fps--319xq on 2025-05-03T19:44:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fps--319xq'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
